### ISSUE TITLE
Explore rollup-plugin-visualizer

### ISSUE THREAD

**Issue by jaredpalmer** [formium/tsdx#496]
Seems useful. Perhaps we add an `--inspect` flag?

**Comment by arvinsim** [comment]
Were you guys able to make `rollup-plugin-visualizer` work with resorting to the `objectHashIgnoreUnknownHack` hack to circumvent the `asyncfunction` issue?

**Comment by agilgur5** [comment]
@arvinsim I'm fairly certain your hunch is correct that this is blocked on https://github.com/puleos/object-hash/pull/90 .
In theory disabling `rpts2`'s cache _only_ during `--inspect` isn't that bad, but I'm not a big fan of adding a hack on top of a hack to the codebase as that can lead to unexpected issues, esp. when they involve caching.

**Comment by agilgur5** [comment]
Ok so https://github.com/puleos/object-hash/pull/90 was just merged and released so now we're blocked on https://github.com/ezolenko/rollup-plugin-typescript2/pull/203 (PR from me).

Notably, `rollup-plugin-visualizer` was mentioned in #200 as an explicit example of one of the things that wasn't possible due to `rpts2`'s lack of async/await support.

I mentioned in https://github.com/puleos/object-hash/pull/90 that it'd be difficult to fork/patch a transitive dependency, but this actually goes a step further as `rpts2` doesn't have externals for its dependencies and actually _bundles_ them in its own release (https://github.com/ezolenko/rollup-plugin-typescript2/pull/80, https://github.com/ezolenko/rollup-plugin-typescript2/pull/70), so TSDX _can't_ override the version of `object-hash` that `rpts2` uses (on top of having duplicated dependencies included in it...) 😕 😕
