### ISSUE TITLE
How do I get it to work with "@import"

### ISSUE THREAD

**Issue by jauggy** [formium/tsdx#827]
I get the error:
```
Module parse failed: Unexpected character '@' (9:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

**Comment by agilgur5** [comment]
Please don't remove the issue template, it's there for a reason and would have been quite useful here...

Your error is coming from Webpack, which is not part of TSDX, so I have no idea how or if this is even related from so few details.

`@import` is also CSS syntax, not TS/JS. TSDX does not touch CSS on its own either, you must add a Rollup plugin for something like that

Without significantly more details, this seems like an invalid issue in the wrong repo

**Comment by jauggy** [comment]
I'll do more investigation and try adding Rollup plugin.

I was confused what issue template to use since it is neither a bug report nor a feature request (the two templates you have). It's simply a question.

Thanks for your help anyway.

**Comment by agilgur5** [comment]
> I'll do more investigation and try adding Rollup plugin.

Ok I mean I still have absolutely no idea what the problem is because you didn't provide a reproduction and your error is from Webpack, not TSDX or Rollup. I was just writing how things generally work

> I was confused what issue template to use since it is neither a bug report nor a feature request (the two templates you have). It's simply a question.

You listed an error message so I would think you were filing a bug report. But that error is not from TSDX, it's from Webpack.

If you had a pure question I would suggest looking at the docs, StackOverflow, etc first. If none are sufficient then could file a request to improve the docs regarding the topic of your question. But ideally we'd want to direct questions and support to StackOverflow or GitHub Discussions (which I don't think is generally available yet) as opposed to issues which are mainly for bugs and features.
