### ISSUE TITLE
Support for Preact templates?

### ISSUE THREAD

**Issue by LXSMNSYC** [formium/tsdx#840]
TSDX is a great tool for building packages and I look forward into continuing developing packages using it. However, given that TSDX supports a React template with or without Storybook, are there any plans on adding template for Preact projects?

**Comment by agilgur5** [comment]
Please don't remove the issue template, it is there for a reason.

The `react-with-storybook` template is entirely community contributed, with each version even having a separate author.

I'd welcome a contribution for Preact use as well.
There will likely be some complexity to it since TSDX was designed with React in mind, so things like TS pragmas, Babel plugins, ESLint plugins, etc have React nuances to them.
