### ISSUE TITLE
Dependabot YAML is invalid

### ISSUE THREAD

**Issue by jaredpalmer** [formium/tsdx#849]
### Current Behavior

Not sure Dependabot is configured correctly. Seeing this message in the dependabot tab: https://github.com/formium/tsdx/network/updates tab 

![image](https://user-images.githubusercontent.com/4060187/91741352-96699880-eb82-11ea-8986-0c8590ede57d.png)

### Expected behavior

No error message or warnings. 

### Suggested solution(s)

Ensure that YAML is valid. Check the whitespace.

**Comment by agilgur5** [comment]
The YAML is quite valid and I ran it through a YAML repl and have a YAML linter in my editor (do a lot of k8s work). Per the error given, it has nothing to do with whitespace, the problem is that GitHub apparently doesn't support YAML aliases and doesn't document this anywhere either or provide a linter for its variant of YAML (the [link it gives](https://jsonformatter.org/yaml-validator) is a third-party linter). There's no way of testing it which I mentioned in #846.

I'll have to duplicate the config then since you can't use aliases/anchors 😕 . Thanks for the bug report, will get to it later

**Comment by agilgur5** [comment]
Seems to be working now: https://github.com/formium/tsdx/network/updates
