### ISSUE TITLE
(internal) Add Kodiak

### ISSUE THREAD

**Issue by jaredpalmer** [formium/tsdx#891]
Been using https://kodiakhq.com on Formik and it really helps. I think it would help out a lot as you can approve a PR and it will automerge it once checks have finished and update other PRs as well. It's really really useful. 

@agilgur5 Let me know if you want me to set it up. It requires protecting master and making certain tests required. If you want to see the impact checkout https://github.com/vercel/next.js, https://github.com/formium/formik, or this https://github.com/jaredpalmer/tsdx-monorepo I put together.

**Comment by agilgur5** [comment]
Thanks for the recommendation. Updating PRs is potentially useful a la [Bors](https://github.com/bors-ng/bors-ng), but auto-merging would not be because I do a rebase merge or a squash merge pending the PR (if it is organized as independent commits or not), and with squash merges and contributor PRs, I am often re-writing the description since the PR/commit descriptions do not tend to be detailed or change over the lifetime of the PR.

It looks like it may also add a comment, which I'm not a fan of -- I've gotten [~200+ unnecessary notifications](https://github.com/formium/tsdx/issues/848#issuecomment-683890726)) from the Vercel bot (the vast majority of which don't even touch the website), which is extremely annoying and frustrating to me and some other contributors.

**Comment by agilgur5** [comment]
> It requires protecting master and making certain tests required

I would quite like to have branch protection set-up and make tests required in any case, as I've mentioned in https://github.com/formium/tsdx/issues/702#issuecomment-660696221 . If you could set that up or make me a member such that I can do that myself, that would be helpful.
I'd have to leave admin override on for reviewer rule though since no one is available to review my PRs.
