### ISSUE TITLE
Node.js 14 (node:15731) Warning: Accessing non-existent property of module exports inside circular dependency (Use `node --trace-warnings ...` to show where the warning was created)

### ISSUE THREAD

**Issue by JustFly1984** [formium/tsdx#910]
Running the build command displays multiple warnings.

```zsh
(node:15731) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15731) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:15731) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:15731) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:15731) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:15731) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:15731) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:15731) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:15731) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:15731) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:15731) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:15731) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:15731) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:15731) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:15731) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:15731) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:15731) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:15731) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:15731) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:15731) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:15731) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:15731) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:15731) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:15731) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:15731) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:15731) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:15731) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:15731) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:15731) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
```

my npm script looks like this:

```json
{
"build": "npx tsdx build --name infoBox --format=cjs,esm,umd",
}
```

Environment - node 14.13.1
webpack 5.2.0

**Comment by agilgur5** [comment]
@JustFly1984 I'm not sure why you removed the issue template this time, but please don't do that, it's there for a reason

> Environment - node 14.13.1
> webpack 5.2.0

In particular, there's a specific command that is asked for all bug reports to use which gives all the required versions (TS, TSDX, etc). You used it in #900.

Webpack is also unrelated to TSDX so I'm not sure what you meant with that.

> Running the build command displays multiple warnings.

This looks to be specific to Node 14, but not quite specific to TSDX. Similar to your #900 this seems to be a lockfile issue as this is coming from `shelljs` and should be fixed in the latest version of `shelljs`, which is [_not_ pinned by TSDX](https://github.com/agilgur5/tsdx/blob/422ca59e64f77f182e58b49279dc5a73c3e26436/package.json#L95).

I did [a search for this exact warning](https://www.google.com/search?q=(node%3A15731)+Warning%3A+Accessing+non-existent+property+%27cat%27+of+module+exports+inside+circular+dependency) and the first result pointed to a Node issue, https://github.com/nodejs/node/issues/32987. There is a mention of `shelljs`, which is what exports all those shell-sounding names, in a comment there: https://github.com/nodejs/node/issues/32987#issuecomment-635726114 . That points to https://github.com/shelljs/shelljs/pull/973 and says it should be solved by upgrading to `shelljs` v0.8.4.

It's pinned to [v0.8.3 in your `yarn.lock`](https://github.com/JustFly1984/react-google-maps-api/blob/d7403fc16351fcfc00ad573faf55e3d02f677d2d/packages/react-google-maps-api-infobox/yarn.lock#L7521), so you can just change it there.

Please recognize that filing an issue is asking a volunteer to respond. Please try to debug and search whatever problem you're having before filing an issue as both this and #900 were problems upstream and are specific to your lockfile. If you do file an issue, please make sure to fill out the issue template, search existing issues for duplicates, and try to narrow down why this is an issue in TSDX specifically and not elsewhere. Other maintainers could close such issues outright for not providing this information as [we don't have the resources / capacity to debug every users' issues](https://github.com/formium/tsdx/issues/461#issuecomment-579050218)

### Internal Repro

This also affects internal tests. I looked through [the CI logs](https://github.com/formium/tsdx/pull/904/checks?check_run_id=1252503025) and saw this happens on Node 14 tests as well because the internal `yarn.lock` (which does not affect TSDX users and is not published) [also has `shelljs` v0.8.3 pinned](https://github.com/formium/tsdx/blob/422ca59e64f77f182e58b49279dc5a73c3e26436/yarn.lock#L7430).
