### ISSUE TITLE
How do I use Mocha with TSDX?

### ISSUE THREAD

**Issue by dgreene1** [formium/tsdx#921]
I'm putting this information here in case anyone else is looking to do this:

Solution:
1. modify your package.json to use the example provided [here](https://github.com/mochajs/mocha-examples/tree/master/packages/typescript-babel)
2. following the instructions [here](https://stackoverflow.com/questions/64669892/how-do-i-hide-the-jest-types-so-i-can-use-mocha/64669893#64669893) so you can ignore the Jest types

**Comment by dgreene1** [comment]
Self-answered

**Comment by agilgur5** [comment]
You can also [use `--require ts-node/register`](https://mochajs.org/#-require-module-r-module), though it is slower than just compiling then running tests.

**Comment by dgreene1** [comment]
Thanks, yes. The main reason I made this post is to share that you have to resort to some unique hacks to get the Jest types out of the way. I describe that more in detail in the [second link](https://stackoverflow.com/questions/64669892/how-do-i-hide-the-jest-types-so-i-can-use-mocha/64669893#64669893) I placed above.

**Comment by agilgur5** [comment]
Yea that's suboptimal experience. I've been looking to split up the commands for a while now (e.g. #407 is an initial step toward that) so that if you wanted to, instead of installing `tsdx`, you install `@tsdx/rollup` and `@tsdx/eslint` but not `@tsdx/jest` in this case. That would also open it up for a `@tsdx/mocha` for instance too.
