### ISSUE TITLE
material-ui library development slow

### ISSUE THREAD

**Issue by xiaoyu-tamu** [formium/tsdx#934]
Anyone ideas how to speed up build when building component library on top of material-ui?

```
"peerDependencies": {
    "react": ">=16",
    "@emotion/core": "latest",
    "@emotion/styled": "latest",
    "@material-ui/core": "next",
    "@material-ui/icons": "next",
    "@material-ui/lab": "next"
  },
  "devDependencies": {
    "@emotion/core": "latest",
    "@emotion/styled": "latest",
    "@material-ui/core": "next",
    "@material-ui/icons": "next",
    "@material-ui/lab": "next",
}
```

### Current Behavior
It takes about 90 seconds to build a simple material-ui component library
![image](https://user-images.githubusercontent.com/33362998/98842452-3eb39d00-240f-11eb-98bb-fd1356fbd240.png)

### Expected behavior

It should be faster

### Your environment

```text

```

**Comment by agilgur5** [comment]
Could you provide a minimal reproduction of this? Build time typically only grows with the size of your source code (especially if `skipLibCheck` is turned on, which seems to happen regardless for rpts2 per https://github.com/ezolenko/rollup-plugin-typescript2/issues/212) unless you've configured `tsdx.config.js` to bundle external dependencies.

Your issue is also missing environment details, so it's unclear what version you're on. There have been several performance improvements in recent versions.

**Comment by agilgur5** [comment]
Closing as stale
