### ISSUE TITLE
@babel/core v7.13.0 bugs causing builds to fail on new installs

### ISSUE THREAD

**Issue by marklawlor** [formium/tsdx#977]
### Current Behavior

```
npx tsdx create my-project
```
Choose `react with storybook`

Errors during the build phase with 

```
(babel plugin) TypeError: Cannot read property 'resolved' of undefined
TypeError: Cannot read property 'resolved' of undefined
    at /home/user/my-project/node_modules/tsdx/dist/babelPluginTsdx.js:19:94
    at Array.findIndex (<anonymous>)
    at /home/user/my-project/node_modules/tsdx/dist/babelPluginTsdx.js:19:54
    at Array.forEach (<anonymous>)
    at /home/user/my-project/node_modules/tsdx/dist/babelPluginTsdx.js:18:27
    at Array.forEach (<anonymous>)
    at Object.exports.mergeConfigItems (/home/user/my-project/node_modules/tsdx/dist/babelPluginTsdx.js:17:24)
    at Object.config (/home/user/my-project/node_modules/tsdx/dist/babelPluginTsdx.js:109:40)
    at transformCode (/home/user/my-project/node_modules/@rollup/plugin-babel/dist/index.js:239:86)
    at async Promise.all (index 0)

```

It appears the latest version of `@babel/core` broke the config merging.

### Expected behavior

TSDX can create new projects

### Suggested solution(s)

Current workaround is to lock `package.json` to `"@babel/core": "7.12.17"` via resolutions

```
"resolutions": {
  "**/@babel/core": "7.12.17"
}
```

### Your environment

```text
System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 5.76 GB / 15.37 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.19.0/bin/npm
  Browsers:
    Chrome: 88.0.4324.182
    Firefox: 85.0.1

```

**Comment by marklawlor** [comment]
This seems to fix the build, but the Storybook is failing with

**Comment by marklawlor** [comment]
Related babel issue https://github.com/babel/babel/issues/12854

**Comment by hzoo** [comment]
@marklawlor yep looks like the same issue with `createConfigItem`, so should be fixed soon https://github.com/formium/tsdx/blob/462af2d002987f985695b98400e0344b8f2754b7/src/babelPluginTsdx.ts#L1

**Comment by agilgur5** [comment]
> It appears the latest version of `@babel/core` broke the config merging.

Yes, `@babel/core` v7.13.0 was released just two hours ago and seems to have several bugs. https://github.com/babel/babel/issues/12851 is this error and https://github.com/babel/babel/issues/12852 recently fixed it.

It is an upstream bug in Babel that many packages are hitting; it's not something TSDX can control. It's also incredibly recent and likely to be fixed by tomorrow if not within the next few hours.

> Current workaround is to lock `package.json` to `"@babel/core": "7.12.17"` via resolutions

You can also set your `yarn.lock` or `package-lock.json`. TSDX does not pin a newer version.

> but the Storybook is failing with

That is also a bug in Babel, https://github.com/babel/babel/issues/12854, that was closed 5 minutes ago in https://github.com/babel/babel/issues/12855.

TSDX does not even depend on Storybook, it's just in one of the templates, so a bug in Storybook is also not something TSDX can control. But neither can Storybook as that's a bug in Babel.

Would recommend focusing time upstream, but thanks for providing a workaround @marklawlor that should suffice for anyone installing within the next day or so until this is fixed upstream

**Comment by hzoo** [comment]
> It's also incredibly recent and likely to be fixed by tomorrow if not within the next few hours.

@agilgur5, yep publishing a new version now! https://github.com/babel/babel/runs/1957418439

**Comment by hzoo** [comment]
Ah it published when I posted, it should be fixed if you try again https://github.com/babel/babel/releases/tag/v7.13.1

**Comment by agilgur5** [comment]
Thanks @hzoo, y'all rock!

**Comment by agilgur5** [comment]
@marklawlor if you could confirm the fix and close out, that'd be great. I think the added tests in the Babel PRs cover our use-cases, but might find something else -- please report upstream to help the Babel team if so.

**Comment by derrickmehaffy** [comment]
Hi from another node project Strapi o/

We tested v7.13.1 and it did not fix it for us, we issued a workaround for our community here: https://github.com/strapi/strapi/issues/9482#issuecomment-783797102

**Comment by marklawlor** [comment]
@agilgur5 v7.13.1 works for a clean install.

@derrickmehaffy cheers that fixed the last issue with my project
