### ISSUE TITLE
tree-shaking doesn't work well for UMD bundle with axios and dayjs

### ISSUE THREAD

**Issue by zerofront** [formium/tsdx#992]
### Current Behavior

I used tsdx to create a project A, and import axios, dayjs, and export. then I use tsdx to create project B and import some function from project A, but not using axios, dayjs. and I find axios/dayjs code in project B UMD bundle

##### project A
`tsdx create A (select basic)`

change src/index.ts

```typescript
import dayjs from 'dayjs'
import axios from 'axios'

const sum = (a: number, b: number) => {
  console.log('boop');
  return a + b;
};

const minus = (a: number, b: number) => {
  console.log('poop');
  return a - b;
};

export {
  sum,
  minus,
  dayjs,
  axios,
}
```

`npm publish`

#### project B
`tsdx create B (select basic)`

change src/index.ts

```typescript
import { minus } from 'A'

function final(a: number, b: number) {
  return minus(a, b)
}

export {
  final
}
```

change project b tsdx.config.js 
```javascript
module.exports = {
  rollup(config) {
    if (config.output.format === 'umd') {
      delete config.external;
    }
    return config;
  }
}
```

*Check UMD bundle, although I did not use axios, the bundle has this part of the code*

**Comment by agilgur5** [comment]
So you've again removed the issue template here, despite that is not supposed to be removed and despite that I explicitly asked you in https://github.com/formium/tsdx/issues/989#issuecomment-795549389 to not remove the issue template. I'll ask again for you to please stop removing it. Further non-compliance will result in auto-closes.

**Comment by agilgur5** [comment]
So tree-shaking _in general_ is highly application specific, and not a "it works or not" type of thing. [Rollup itself has a section in the docs about it](https://rollupjs.org/guide/en/#tree-shaking-doesnt-seem-to-be-working).

Rollup has tree-shaking turned on by default and only has [a few configurations for it](https://rollupjs.org/guide/en/#treeshake). TSDX actually adds some other optimizations (like [`propertyReadSideEffects`](https://github.com/formium/tsdx/blob/462af2d002987f985695b98400e0344b8f2754b7/src/createRollupConfig.ts#L72) and [`babel-plugin-annotate-pure-calls`](https://github.com/formium/tsdx/blob/462af2d002987f985695b98400e0344b8f2754b7/src/babelPluginTsdx.ts#L72)) to potentially add more ability to tree-shake.

So there is not really much TSDX can do to further improve that. There is `preserveModules` in #276, but that has no impact on a single tiny file build like your example here. Rollup 2 in #889 may have some improvements.
You can also make more aggressive assumptions for tree-shaking at your own risk by modifying the Rollup config in `tsdx.config.js`.
You will probably get the same results or worse using Rollup directly, but you are welcome to try and give any feedback from there.


> _Check UMD bundle, although I did not use axios, the bundle has this part of the code_

So `dayjs` and `axios` do not seem to be tree-shakeable, [according to](https://bundlephobia.com/result?p=dayjs@1.10.4) [bundlephobia](https://bundlephobia.com/result?p=axios@0.21.1). They both seem to export CJS only and [don't have](https://github.com/iamkun/dayjs/blob/9c20e77caf7b1b5eccf418175203b198d4e29535/package.json) [`sideEffects: false`](https://github.com/axios/axios/blob/5c122b7eaf279ce2b9de2894283aacd062192f17/package.json). `dayjs` seems to have some notes on this here https://github.com/iamkun/dayjs/issues/1281. Couldn't find much [on `axios`'s issues](https://github.com/axios/axios/issues?q=is%3Aissue+is%3Aopen+tree-shaking).

So as I said, tree-shaking is _highly_ application-specific as it depends on your library and your dependencies not having side-effects and enabling tree-shaking with ESM. Rollup by _default_ has it enabled and TSDX by _default_ is a bit more aggressive with its assumptions. There is not really much more that TSDX or Rollup can do.

(I'm also not totally sure how/if tree-shaking works with UMD (or what happens if you have no `externals`). Theoretically it should still work I think.)
